.TH COUNT_WORDS 3
.SH NAME
Count_words - count words in a file

.SH SYNOPSIS
#include <file_utils.h>

int count_words(const char *filename);

.SH DESCRIPTION
count_words reads file and returns the total number
of words present inside the file 

.SH RETURN VALUE
Returns no. of words

.SH AUTHOR
OS PA01

